volumes:
  laravel_app:

services:
  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    image: juniyasyos/siimut-app:alpine-1.3.5
    restart: unless-stopped
    ports:
      - "${VITE_PORT}:5173"
    volumes:
      - laravel_app:/var/www

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - laravel_app:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    # image: mysql:${MYSQL_VERSION}
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./Docker/db/data:/var/lib/mysql
      - ./Docker/logs:/var/log/mysql
      - ./Docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./Docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "${PMA_PORT}:80"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - ./Docker/phpmyadmin/sessions:/sessions

  ####################################################################################################
  # Adminer
  ####################################################################################################
  # adminer:
  #     image: adminer
  #     restart: unless-stopped
        # ports:
  #         - 9090:8080
  #     depends_on:
  #     - db

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  # mail:
  #   image: axllent/mailpit:latest
  #   restart: unless-stopped
  # ports:
  #     - "${MAIL_WEB_PORT}:8025"
  #     - "${MAIL_SMTP_PORT}:1025"

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./Docker/redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"

  ####################################################################################################
  # Laravel Schedule Worker
  ####################################################################################################
  worker:
    image: juniyasyos/siimut-app:alpine-1.3.5
    restart: unless-stopped
    command: >
      sh -c "
        php artisan queue:work redis --sleep=3 --tries=3 &
        php artisan schedule:work
      "
      
  # schedule:
  #   build:
  #     context: ./Docker/php
  #     dockerfile: Dockerfile.alpine
  #   volumes:
  #     - laravel_app:/var/www
  #   command: ["php", "/var/www/artisan", "schedule:work"]
  #   depends_on:
  #     - php
  #     - db
  #     - redis

  # queue:
  #   build:
  #     context: ./Docker/php
  #     dockerfile: Dockerfile.alpine
  #   volumes:
  #     - laravel_app:/var/www
  #   command: ["php", "/var/www/artisan", "queue:work", "redis", "--sleep=3", "--tries=3"]
  #   depends_on:
  #     - php
  #     - redis

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     restart: unless-stopped
  # ports:
  #         - 3306:3306
  #     volumes:
  #         - Docker/db/data:/var/lib/mysql
  #         - Docker/logs:/var/log/mysql
  #         - Docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - Docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  # db:
  #     image: postgres:16
  #     restart: unless-stopped
  # ports:
  #         - 5432:5432
  #     volumes:
  #         - Docker/db/data:/var/lib/postgresql/data
  #         - Docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         - POSTGRES_USER=refactorian
  #         - POSTGRES_PASSWORD=refactorian
  #         - POSTGRES_DB=refactorian

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  # pgadmin:
  #     image: dpage/pgadmin4
  #     restart: unless-stopped
  # ports:
  #         - 5050:80
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #         - PGADMIN_DEFAULT_PASSWORD=password
  #     depends_on:
  #         - db
