services:
  node:
    image: node:iron-alpine
    container_name: ${STACK_NAME:-laravel}-node
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./site/${APP_DIR:-tamasuma-backend}:/var/www/html
    command: tail -f /dev/null
    restart: unless-stopped

