services:
  mail:
    image: axllent/mailpit:latest
    container_name: ${STACK_NAME:-laravel}-mail
    ports:
      - "${MAIL_WEB_PORT:-8025}:8025"
      - "${MAIL_SMTP_PORT:-1025}:1025"
    restart: unless-stopped

