services:
  redis:
    image: redis:alpine
    container_name: ${STACK_NAME:-laravel}-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped

volumes:
  redis_data:

